<?php

namespace App\Services;

use App\Interfaces\FabricateInterface;
use Illuminate\Http\Request;

class UserService extends ExcelService implements FabricateInterface
{
    public function store($model, Request $request)
    {
        // TODO: Implement store() method.
    }

    public function delete($model)
    {
        // TODO: Implement delete() method.
    }

    public function export($model)
    {
        return parent::export($model); // TODO: Change the autogenerated stub
    }
}
